version: "3"

services:
  my-prometheus-container:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9091:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    expose:
      - '9300'
  my-grafana-container:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3100:3000'
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - '9100:9100'
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - '8080:8080'

